# Generated by Django 6.0.3 on 2026-03-30 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExtractedInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("language", models.CharField(max_length=50)),
                ("purpose", models.CharField(max_length=100)),
                ("level", models.CharField(max_length=100)),
                ("malayalam", models.CharField(max_length=10)),
                ("malayalam_mode", models.CharField(max_length=100)),
            ],
        ),
    ]
